name: Send SMS on failure
run-name: ${{ github.actor }} wants to sent an SMS
on: [push]
env:
  TOKEN: ${{ secrets.SMS_TOKEN }}
  FROM: ${{ secrets.SMS_FROM }}
  TO: ${{ secrets.SMS_TO }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: explicitly fail this job
        run: exit -1
      - name: send sms if failed
        if: failure()
        run: |
          curl 'https://api.telekom.com/service/sms/v1/messages/' \
            --silent \
            -X 'POST' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -H "X-API-KEY: ${TOKEN}" \
            -d "From=${FROM}&To=%2B${TO}&Body=Build%20failed."
      - name: report success
        if: success()
        run: echo "🎉 success, but why?"
